### ISSUE TITLE
Cards de onboarding

### ISSUE THREAD

**Issue by vitorrgg** [ecomplus/admin-home#5]
Alguns links iniciais podem ajudar muito o lojista em seu primeiro login a conseguir efetuar uma configuração e  ter seu "WOW Moment", aumentando nossa retenção e sucesso desse cara. 

Acredito que o "WoW moment" mais óbvio, é com a criação do produto, por ser de fácil visualização e ser a parte central da loja e maioria dos lojistas já vem sabendo o que pretendem vender. 

Outros dois pontos acredito serem dignos de estarem nesses "cards de onboarding" são com relação a pagamento e frete. Não tendo nenhuma forma de pagamento idealmente linkar para apps de pagamento e com formas de frete a mesma coisa, pois são apps nescessários para o funcionamento da loja. Caso não seja possível filtrar os apps, mandar para a página normal do market acredito que seja de grande ajuda.  

Talvez faça sentido linkar aqui algum tutorial em vídeo ou escrito na comunidade falando de uma forma geral sobre a plataforma, como é o caso [deste vídeo ](https://youtu.be/-PayqoKBs4o).

**Comment by leomp12** [comment]
![Screenshot_2021-02-24  ecomplus admin-home(1)](https://user-images.githubusercontent.com/10326572/109066161-692e1b00-76cb-11eb-9cba-b1f5265fa2b3.png)

Mas se pá a capa desse vídeo aí podia ficar melhorzinha em @vitorrgg

**Comment by leomp12** [comment]
@vitorrgg ele tá aparecendo com resolução ruim no iframe aí, mas até que no YouTube não tá ruim, se pá se souber como resolve isso aí...
